server:
  applicationConnectors:
    - type: http
      port: ${PORT}
  adminConnectors:
    - type: http
      port: ${ADMIN_PORT}

logging:
    level: INFO
    appenders:
      - type: console
        threshold: ALL
        timeZone: UTC
        target: stdout
        logFormat: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n"

links:
  frontendUrl: ${FRONTEND_URL}

worldpay:
  url: ${GDS_CONNECTOR_WORLDPAY_URL}
  credentials: ['username','password','merchant_id']

smartpay:
  url: ${GDS_CONNECTOR_SMARTPAY_URL}
  notification:
    username: ${GDS_CONNECTOR_SMARTPAY_NOTIFICATION_USER}
    password: ${GDS_CONNECTOR_SMARTPAY_NOTIFICATION_PASSWORD}
  credentials: ['username','password']

executorServiceConfig:
  timeoutInSeconds: ${AUTH_READ_TIMEOUT_SECONDS:-1}
  threadsPerCpu: ${NUMBER_OF_THREADS_PER_CPU:-100}

transactionsPaginationServiceConfig:
  displayPageSize: ${TRANSACTION_LIST_DISPLAY_SIZE:-500}

jerseyClient:
  timeout: 25500ms
  connectionTimeout: 25500ms
  timeToLive: 1h
  cookiesEnabled: false
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0ms
  retries: 0
  userAgent: connector
  gzipEnabledForRequests: false
  proxy:
      host: ${HTTP_PROXY_HOST}
      port: ${HTTP_PROXY_PORT}
      scheme : ${HTTP_PROXY_SCHEME}
      nonProxyHosts:
        - localhost

customJerseyClient:
  readTimeout: 90000ms
  enableProxy: ${HTTP_PROXY_ENABLED}

database:
  driverClass: org.postgresql.Driver
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  url: jdbc:postgresql://${DB_HOST}:5432/connector?sslfactory=uk.gov.pay.connector.util.TrustingSSLSocketFactory&${DB_SSL_OPTION}

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "SELECT '1'"

  # the timeout before a connection validation queries fail
  validationQueryTimeout: 2s

  # The initial size of the connection pool
  initialSize: 4

  # the minimum number of connections to keep open
  minSize: 4

  # the maximum number of connections to keep open
  maxSize: 8

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

jpa:
  jpaLoggingLevel: ${JPA_LOG_LEVEL:-WARNING}
  sqlLoggingLevel: ${JPA_SQL_LOG_LEVEL:-WARNING}
  ddlGenerationOutputMode: database
  queryResultsCache: false
  cacheSharedDefault: false

